local S,M,L,T,B,U = Instance.new("ScreenGui"),Instance.new("Frame"),Instance.new("ImageLabel"),Instance.new("TextLabel"),Instance.new("ScrollingFrame"),Instance.new("UIListLayout")
S.Parent,S.Name,S.ResetOnSpawn = game:GetService("CoreGui"),"MenuVermelhoExclusivo",false
M.Name,M.Parent,M.BackgroundColor3,M.BorderColor3,M.BorderSizePixel,M.Position,M.Size,M.Active,M.Draggable = "MainFrame",S,Color3.fromRGB(15,15,15),Color3.fromRGB(255,0,0),2,UDim2.new(0.35,0,0.25,0),UDim2.new(0,350,0,480),true,true
L.Name,L.Parent,L.BackgroundTransparency,L.Size,L.Image,L.ImageTransparency = "LogoBackground",M,1,UDim2.new(1,0,1,0),"rbxassetid://13511874240",0.75
T.Name,T.Parent,T.BackgroundTransparency,T.Position,T.Size,T.Font,T.Text,T.TextColor3,T.TextSize = "Title",M,1,UDim2.new(0,0,0,5),UDim2.new(1,0,0,30),Enum.Font.SourceSansBold,"DARK WOLF V3",Color3.fromRGB(255,0,0),22
B.Name,B.Parent,B.BackgroundTransparency,B.Position,B.Size,B.CanvasSize,B.ScrollBarThickness,B.ScrollBarImageColor3 = "ButtonsContainer",M,1,UDim2.new(0.05,0,0.11,0),UDim2.new(0,315,0,415),UDim2.new(0,0,3.5,0),4,Color3.fromRGB(255,0,0)
U.Parent,U.SortOrder,U.Padding = B,Enum.SortOrder.LayoutOrder,UDim.new(0,10)
local P,R,n,f,j,s,fl,li,fc = game:GetService("Players").LocalPlayer,game:GetService("RunService"),false,false,false,false,false,false,false
local fSp,tSp,tJp,fCn,nCn,fcCn = 50,16,50
local function btn(nm,id,fn,bc)
    local b = Instance.new("TextButton") b.Name,b.Parent,b.BackgroundColor3,b.BorderColor3,b.BorderSizePixel,b.Size,b.Font,b.Text,b.TextColor3,b.TextSize = id,B,bc or Color3.fromRGB(30,5,5),Color3.fromRGB(255,0,0),1,UDim2.new(1,0,0,45),Enum.Font.SourceSansBold,nm,Color3.fromRGB(255,255,255),18
    b.MouseButton1Click:Connect(fn) return b
end
local function txt(ph,pd,fn)
    local c,l,x = Instance.new("Frame"),Instance.new("TextLabel"),Instance.new("TextBox") c.Parent,c.Size,c.BackgroundTransparency = B,UDim2.new(1,0,0,45),1
    l.Parent,l.Size,l.BackgroundTransparency,l.Font,l.Text,l.TextColor3,l.TextSize = c,UDim2.new(0.5,0,1,0),1,Enum.Font.SourceSansBold,ph..":",Color3.fromRGB(255,255,255),18
    x.Parent,x.Position,x.Size,x.BackgroundColor3,x.BorderColor3,x.BorderSizePixel,x.Font,x.Text,x.TextColor3,x.TextSize,x.PlaceholderText = c,UDim2.new(0.5,0,0,0),UDim2.new(0.5,0,1,0),Color3.fromRGB(20,5,5),Color3.fromRGB(255,0,0),1,Enum.Font.SourceSansBold,tostring(pd),Color3.fromRGB(255,0,0),18,ph
    x.FocusLost:Connect(function() local n=tonumber(x.Text) if n then fn(n) end end)
end
local function lbl(txt) local l = Instance.new("TextLabel") l.Parent,l.Size,l.BackgroundTransparency,l.Font,l.Text,l.TextColor3,l.TextSize,l.TextYAlignment = B,UDim2.new(1,0,0,30),1,Enum.Font.SourceSansBold,txt,Color3.fromRGB(255,0,0),16,Enum.TextYAlignment.Bottom return l end
local function dF() f = false if B:FindFirstChild("Fly") then B.Fly.Text = "Fly: OFF" end if fCn then fCn:Disconnect() end local r,h = P.Character and P.Character:FindFirstChild("HumanoidRootPart"),P.Character and P.Character:FindFirstChildOfClass("Humanoid") if r then if r:FindFirstChild("IYFlyBV") then r.IYFlyBV:Destroy() end if r:FindFirstChild("IYFlyBG") then r.IYFlyBG:Destroy() end end if h then h.PlatformStand = false end end
local function dN() n = false if B:FindFirstChild("Noclip") then B.Noclip.Text = "Noclip: OFF" end if nCn then nCn:Disconnect() end end
local function remPart(nt) if P.Character then for _,v in pairs(nt) do local p=P.Character:FindFirstChild(v) if p then p:Destroy() end end end end
R.Heartbeat:Connect(function() local h = P.Character and P.Character:FindFirstChildOfClass("Humanoid") if h then h.WalkSpeed,h.UseJumpPower,h.JumpPower = tSp,true,tJp end end)
txt("WalkSpeed",16,function(v) tSp=v end) txt("JumpPower",50,function(v) tJp=v end)
btn("Noclip: OFF","Noclip",function() n = not n B.Noclip.Text = n and "Noclip: ON" or "Noclip: OFF" if n then dF() nCn = R.Stepped:Connect(function() if not n then nCn:Disconnect() return end if P.Character then for _,v in pairs(P.Character:GetDescendants()) do if v:IsA("BasePart") then v.CanCollide = false end end end end) else if nCn then nCn:Disconnect() end end end)
btn("Jerk: OFF","Jerk",function() j = not j B.Jerk.Text = j and "Jerk: ON" or "Jerk: OFF" task.spawn(function() while j do local t = P.Character and (P.Character:FindFirstChild("Torso") or P.Character:FindFirstChild("LowerTorso")) local r = t and (t:FindFirstChild("RootJoint") or P.Character.HumanoidRootPart:FindFirstChild("RootJoint")) if r then r.C0 = r.C0 * CFrame.new(0,0,-0.5) task.wait(0.1) r.C0 = r.C0 * CFrame.new(0,0,0.5) task.wait(0.1) else task.wait(0.5) end end local t = P.Character and (P.Character:FindFirstChild("Torso") or P.Character:FindFirstChild("LowerTorso")) local r = t and (t:FindFirstChild("RootJoint") or P.Character.HumanoidRootPart:FindFirstChild("RootJoint")) if r then r.C0 = CFrame.new(0,0,0) * CFrame.Angles(-math.pi/2,0,math.pi) end end) end)
btn("Fly: OFF","Fly",function() f = not f B.Fly.Text = f and "Fly: ON" or "Fly: OFF" local r,h = P.Character and P.Character:FindFirstChild("HumanoidRootPart"),P.Character and P.Character:FindFirstChildOfClass("Humanoid") if not r or not h then return end if f then dN() h.PlatformStand = true local bv,bg = Instance.new("BodyVelocity"),Instance.new("BodyGyro") bv.Name,bv.MaxForce,bv.Velocity,bv.Parent = "IYFlyBV",Vector3.new(1,1,1)*math.huge,Vector3.new(0,0,0),r bg.Name,bg.MaxTorque,bg.CFrame,bg.Parent = "IYFlyBG",Vector3.new(1,1,1)*math.huge,r.CFrame,r fCn = R.Heartbeat:Connect(function() if not f or not r or not r.Parent then dF() return end local c,m = workspace.CurrentCamera,h.MoveDirection if m.Magnitude > 0 then local fD = (c.CFrame.LookVector * m:Dot(c.CFrame.LookVector)) + (c.CFrame.RightVector * m:Dot(c.CFrame.RightVector)) bv.Velocity = fD.Unit * fSp else bv.Velocity = Vector3.new(0,0,0) end bg.CFrame = c.CFrame end) else dF() end end)
btn("Mudar FOV","FOV",function() s = not s workspace.CurrentCamera.FieldOfView = s and 120 or 70 end)
btn("Spin","Spin",function() s = not s local r = P.Character and P.Character:FindFirstChild("HumanoidRootPart") if r then if s then local a = Instance.new("BodyAngularVelocity",r) a.Name,a.MaxTorque,a.AngularVelocity = "SpinningVelocity",Vector3.new(0,math.huge,0),Vector3.new(0,45,0) else if r:FindFirstChild("SpinningVelocity") then r.SpinningVelocity:Destroy() end end end end)
btn("Fling","Fling",function() fl = not fl local r = P.Character and P.Character:FindFirstChild("HumanoidRootPart") if r then if fl then local b = Instance.new("BodyVelocity",r) b.Name,b.MaxForce,b.Velocity = "FlingVelocity",Vector3.new(1,0,1)*math.huge,Vector3.new(20000,0,20000) else if r:FindFirstChild("FlingVelocity") then r.FlingVelocity:Destroy() end end end end)
btn("Light: OFF","Light",function() li = not li B.Light.Text = li and "Light: ON" or "Light: OFF" local r = P.Character and P.Character:FindFirstChild("HumanoidRootPart") if r then if li then local l = Instance.new("PointLight",r) l.Name,l.Color,l.Range,l.Brightness = "WolfLight",Color3.fromRGB(255,0,0),30,5 else if r:FindFirstChild("WolfLight") then r.WolfLight:Destroy() end end end end)
btn("Creeper","Creeper",function() remPart({"Left Arm","Right Arm","LeftUpperArm","RightUpperArm","LeftLowerArm","RightLowerArm","LeftHand","RightHand"}) local t = P.Character and (P.Character:FindFirstChild("Torso") or P.Character:FindFirstChild("UpperTorso")) if t then t.Size = Vector3.new(1,1,1) end end)
btn("NoArms","NoArms",function() remPart({"Left Arm","Right Arm","LeftUpperArm","RightUpperArm","LeftLowerArm","RightLowerArm","LeftHand","RightHand"}) end)
btn("NoLegs","NoLegs",function() remPart({"Left Leg","Right Leg","LeftUpperLeg","RightUpperLeg","LeftLowerLeg","RightLowerLeg","LeftFoot","RightFoot"}) end)
btn("Freecam: OFF","Freecam",function() fc = not fc B.Freecam.Text = fc and "Freecam: ON" or "Freecam: OFF" local c = workspace.CurrentCamera local h = P.Character and P.Character:FindFirstChildOfClass("Humanoid") if fc then if h then h.WalkSpeed = 0 end c.CameraType = Enum.CameraType.Custom local fPart = Instance.new("Part", workspace) fPart.Name, fPart.Size, fPart.Transparency, fPart.Anchored, fPart.CanCollide = "WolfFC", Vector3.new(1,1,1), 1, true, false fPart.CFrame = c.CFrame c.CameraSubject = fPart fcCn = R.RenderStepped:Connect(function() if not fc or not fPart then fcCn:Disconnect() return end local m = h and h.MoveDirection or Vector3.new() if m.Magnitude > 0 then local fAmount = m:Dot(c.CFrame.LookVector) local rAmount = m:Dot(c.CFrame.RightVector) local moveDir = (c.CFrame.LookVector * fAmount) + (c.CFrame.RightVector * rAmount) fPart.CFrame = fPart.CFrame + (moveDir.Unit * 1.5) end end) else if fcCn then fcCn:Disconnect() end c.CameraType = Enum.CameraType.Custom if h then h.WalkSpeed = tSp c.CameraSubject = h end if workspace:FindFirstChild("WolfFC") then workspace.WolfFC:Destroy() end end end)
btn("Day","Day",function() game:GetService("Lighting").TimeOfDay = "14:00:00" end)
btn("Night","Night",function() game:GetService("Lighting").TimeOfDay = "00:00:00" end)
lbl("RECOMMENDED SCRIPTS")
btn("M7 Admin","M7",function() loadstring(game:HttpGet("https://rawscripts.net/raw/Universal-Script-M7-ADMIN-202724"))() end, Color3.fromRGB(15,30,15))
btn("Infinite Yield","IY",function() loadstring(game:HttpGet("https://rawscripts.net/raw/Universal-Script-Infinite-Yield-FE-239454"))() end, Color3.fromRGB(15,30,15))
btn("NeptuneHub","Neptune",function() loadstring(game:HttpGet("https://rawscripts.net/raw/Universal-Script-NeptuneHub-41511"))() end, Color3.fromRGB(15,30,15))
